

    # page.get_by_role("link", name=" Missed Sessions").click()
    # page.locator("#chkAll").check()
    # page.get_by_role("button", name="RUN TSA").click()
    # page.get_by_role("button", name="Refresh").click()
    # page.locator("#checkbox_12018217").check()
    # page.get_by_role("button", name="Assign Tutor").click()
    # page.locator("#select2-ddlActiveTutors-container").click()
    # page.get_by_role("searchbox").fill("fev")
    # page.get_by_role("option", name="fevqamateletutor013 13 (fevqamateletutor013 - fevqamateletutor013)").click()
    # page.once("dialog", lambda dialog: dialog.dismiss())
    # page.get_by_text("Assign", exact=True).click()
    # page.get_by_role("button", name="Refresh").click()
    # page.get_by_role("button", name="Refresh").click()
    # page.get_by_role("button", name="Refresh").click()
    # page.get_by_role("button", name="Refresh").click()
    # page.get_by_role("button", name="Refresh").click()
    # page.get_by_role("button", name="Refresh").click()
    # page.get_by_role("link", name=" Missed UnAsiggned Sessions").click()
    # page.locator("#checkbox_12018217").check()
    # page.get_by_role("button", name="Assign Tutor").click()
    # page.get_by_title("Select Tutor").click()
    # page.locator("a").filter(has_text="fevqamateletutor013 13 (fevqamateletutor013 - fevqamateletutor013)").click()
    # page.once("dialog", lambda dialog: dialog.dismiss())
    # page.get_by_text("Assign", exact=True).click()